using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ScrawlDataIntraday.Common
{
    public class ConstStock
    {
        public static List<string> fullStokcs = new List<string>() { "TDC", "BTS", "CRE", "CTF", "TEG", "NDN", "HHP", "EVS", "MSH", "IPA", "DC4", "IVS", "PTB", "SCS", "PAC", "SJD", "S99", "PVB", "PSI", "SHI", "BCC", "STK", "PHR", "KOS", "TIP", "SGR", "PLC", "CKG", "DHC", "VC7", "TVB", "NTP", "BMI", "BWE", "SIP", "VC3", "HT1", "VCS", "VFS", "QCG", "LHG", "DCL", "VPH", "DL1", "MIG", "BFC", "NTL", "CNG", "FRT", "BCM", "VGC", "PPC", "ITC", "VGS", "FCN", "NHH", "TNH", "TSC", "BVS", "LAS", "CTR", "HBC", "VPG", "OGC", "GSP", "NT2", "BSI", "SKG", "ACV", "C4G", "DDV", "DGT", "LTG", "QNS", "TCI", "VGI", "VGT", "VTP", "SMC", "REE", "BVH", "TCD", "PNJ", "KDC", "TVC", "HAX", "TV2", "FIT", "LSS", "GEG", "DLG", "VPI", "DPR", "CCL", "CSV", "NHA", "GIL", "CMX", "DRC", "VJC", "VIP", "PVP", "CTI", "MBG", "VLC", "DPG", "ADS", "AGG", "TVN", "APS", "CTS", "DXP", "HTN", "TTF", "DTD", "TVS", "SCR", "PAN", "CTD", "VHC", "API", "NAB", "SAM", "TLH", "GAS", "IDC", "SZC", "OIL", "VDS", "VTO", "PVC", "NLG", "SSB", "GMD", "CMG", "DGW", "DGC", "SAB", "VCB", "PET", "ITA", "OCB", "SBT", "LDG", "PSH", "BID", "YEG", "ANV", "FTS", "PLX", "IDJ", "DXS", "VIC", "EVG", "AGR", "HDC", "LCG", "HHS", "KSB", "ELC", "KHG", "BAF", "HUT", "HPX", "APH", "TCM", "TNG", "IDI", "MBS", "ASM", "HVN", "KDH", "VNM", "GVR", "CEO", "HQC", "HHV", "PC1", "CII", "PVD", "VOS", "DPM", "LPB", "PVS", "DBC", "TIG", "PVT", "DCM", "ORS", "KBC", "MSB", "MWG", "DXG", "VCG", "MSN", "VIB", "HDB", "AAA", "FPT", "VCI", "HAH", "IJC", "PDR", "HCM", "BSR", "NKG", "HNG", "VRE", "EIB", "TCH", "HDG", "VHM", "ACB", "TCB", "BCG", "CTG", "EVF", "VND", "NVL", "DIG", "VSC", "HSG", "STB", "TPB", "GEX", "HAG", "SHS", "POW", "SSI", "MBB", "HPG", "VIX", "SHB", "VPB" };
        
        public static List<string> popularStocks = new List<string>() { "VPB", "SHB", "HPG", "MBB", "GEX", "HSG", "POW", "VIX", "HAG", "TPB", "VND", "STB", "SSI", "SHS", "DIG", "TCH", "EVF", "TCB", "HCM", "BCG", "CTG", "HDG", "VRE", "NVL", "ACB", "VSC", "PDR", "MWG", "NKG", "VHM", "HDB", "FPT", "MSN", "MSB", "EIB", "HAH", "DBC", "DCM", "VIB", "DXG", "VCG", "HVN", "HHS", "VCI", "KBC", "CII", "DPM", "DGC", "HQC", "PVS", "PC1", "CEO", "LPB", "VOS", "AAA", "HNG", "IJC", "GVR", "ELC", "VNM", "PVT", "PVD", "ORS", "HHV", "MBS", "SSB", "KDH", "TCM", "TIG", "TNG", "LCG", "KHG", "EVG", "BAF", "ASM", "HUT", "APH", "IDJ", "HDC", "CMG", "HPX", "DXS", "KSB", "VIC", "OCB", "BID", "NLG", "AGR", "IDI", "HTN", "PLX", "VHC", "ANV", "VCB", "SAB", "FTS", "CTD", "TVS", "DGW", "PET", "VDS", "PAN", "ITA", "SZC", "SBT", "SCR", "CTS", "CMX", "IDC", "SAM", "GAS", "VTO", "DPG", "TTF", "GMD", "AGG", "VIP", "DTD", "VPI", "CTI", "NHA", "GEG", "NT2", "TCD", "LAS", "VPG", "GIL", "PVP", "BVH", "DRC", "PNJ", "HAX", "TVC", "NHH" };

        public static List<string> DefaultStocks = new List<string>() { "TDC", "BTS", "CRE", "CTF", "TEG", "NDN", "HHP", "EVS", "MSH", "IPA", "DC4", "IVS", "PTB", "SCS", "PAC", "SJD", "S99", "PVB", "PSI", "SHI", "BCC", "STK", "PHR", "KOS", "TIP", "SGR", "PLC", "CKG", "DHC", "VC7", "TVB", "NTP", "BMI", "BWE", "SIP", "VC3", "HT1", "VCS", "VFS", "QCG", "LHG", "DCL", "VPH", "DL1", "MIG", "BFC", "NTL", "CNG", "FRT", "BCM", "VGC", "PPC", "ITC", "VGS", "FCN", "NHH", "TNH", "TSC", "BVS", "LAS", "CTR", "HBC", "VPG", "OGC", "GSP", "NT2", "BSI", "SKG", "ACV", "C4G", "DDV", "DGT", "LTG", "QNS", "TCI", "VGI", "VGT", "VTP", "SMC", "REE", "BVH", "TCD", "PNJ", "KDC", "TVC", "HAX", "TV2", "FIT", "LSS", "GEG", "DLG", "VPI", "DPR", "CCL", "CSV", "NHA", "GIL", "CMX", "DRC", "VJC", "VIP", "PVP", "CTI", "MBG", "VLC", "DPG", "ADS", "AGG", "TVN", "APS", "CTS", "DXP", "HTN", "TTF", "DTD", "TVS", "SCR", "PAN", "CTD", "VHC", "API", "NAB", "SAM", "TLH", "GAS", "IDC", "SZC", "OIL", "VDS", "VTO", "PVC", "NLG", "SSB", "GMD", "CMG", "DGW", "DGC", "SAB", "VCB", "PET", "ITA", "OCB", "SBT", "LDG", "PSH", "BID", "YEG", "ANV", "FTS", "PLX", "IDJ", "DXS", "VIC", "EVG", "AGR", "HDC", "LCG", "HHS", "KSB", "ELC", "KHG", "BAF", "HUT", "HPX", "APH", "TCM", "TNG", "IDI", "MBS", "ASM", "HVN", "KDH", "VNM", "GVR", "CEO", "HQC", "HHV", "PC1", "CII", "PVD", "VOS", "DPM", "LPB", "PVS", "DBC", "TIG", "PVT", "DCM", "ORS", "KBC", "MSB", "MWG", "DXG", "VCG", "MSN", "VIB", "HDB", "AAA", "FPT", "VCI", "HAH", "IJC", "PDR", "HCM", "BSR", "NKG", "HNG", "VRE", "EIB", "TCH", "HDG", "VHM", "ACB", "TCB", "BCG", "CTG", "EVF", "VND", "NVL", "DIG", "VSC", "HSG", "STB", "TPB", "GEX", "HAG", "SHS", "POW", "SSI", "MBB", "HPG", "VIX", "SHB", "VPB", "HCD" };
        public static int NumOfThread = 5;
    }
}
